spring.application.name=chat-app

spring.data.mongodb.uri=mongodb+srv://travel_user:u2qmM45lVCE6gfaS@chatapp.cwzfpee.mongodb.net/?appName=ChatApp
spring.data.mongodb.database=chatdb

server.port=8092

jwt.secret=${JWT_SECRET:ewkjbfiwe237r62378hdbcyuwegr734@&!^%E^&!@TE^&@$^!@vdqvuqytf63&T&^T}
jwt.expirySeconds=2592000

logging.level.org.springframework.web.socket=info
logging.level.com.personal.chat_app=info

logging.level.org.springframework.web=DEBUG
logging.level.org.springframework.security=DEBUG

logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
logging.level.org.springframework.data.mongodb.core.query=DEBUG

supabase.url=https://lerhvdqqznhlbrvucnnp.supabase.co
supabase.service-role-key=<key>
supabase.storage.bucket=chat-attachments

spring.servlet.multipart.max-file-size=100GB
spring.servlet.multipart.max-request-size=100GB
server.tomcat.max-swallow-size=-1
